### ISSUE TITLE
Override environment passed in docker-compose.yaml file

### ISSUE THREAD

**Issue by harrylowkey** [theskumar/python-dotenv#538]
If I pass env variables in docker-compose.yaml file, the env can't override ones that defined in the .env file, the application still got those env ones like this:

```
DATABASE_HOST=localhost
DATABASE_PORT: 27018
REDIS_HOST: localhost
REDIS_PORT: 6380
KEYCLOAK_BASE_URL: http://localhost:8085
```

Here is my docker-compose.yaml file:

```yaml
version: "3.3"
services:
  api:
    build: ./
    volumes:
      - .env:/usr/app/.env
    environment:
      DATABASE_HOST: mongo
      DATABASE_PORT: 27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KEYCLOAK_BASE_URL: http://keycloak:8080
    ports:
      - 8000:3000
   ...
  ```
   
And here is my .env file

```
#Database
DATABASE_CONNECT=mongodb
DATABASE_HOST=localhost
DATABASE_PORT=27018
DATABASE_USER=root
DATABASE_PASSWORD=mongo
DATABASE_NAME=

# Redis config
REDIS_HOST=localhost
REDIS_PORT=6380
REDIS_DATABASE_NAME=0

KEYCLOAK_CONFIDENTIAL_PORT=0
KEYCLOAK_SSL_REQUIRED=external
KEYCLOAK_CONFIDENTIAL_CLIENT_ID=
KEYCLOAK_CLIENT_ID=
KEYCLOAK_REALM=
KEYCLOAK_BASE_URL=http://localhost:8085
KEYCLOAK_CONFIDENTIAL_CLIENT_SECRET=
```
